name: Reusable workflow example

on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
    secrets:
      test_api_key:
        required: false

jobs:
  example_job:
    name: Run some job
    runs-on: ubuntu-latest
    outputs:
      run-tests: ${{ steps.check-run-tests.outputs.run-tests }}
    steps:
      - uses: actions/checkout@v3
      - name: Run some task
        id: check-run-tests
        uses: ./.github/actions/run-some-task
        with:
          target: ${{ inputs.domain }}

  test_job:
    if: ${{ needs.example_job.outputs.run-tests != 'false' }}
    name: Example test job
    runs-on: ubuntu-latest
    needs: [example_job]
    env:
      API_KEY: ${{ secrets.test_api_key }}
    steps:
      - name: Check run tests
        continue-on-error: true
        run: |
          echo "Ran some tests for ${{ inputs.domain }} with ${API_KEY}"
          exit 1
        shell: bash
      - name: Override exit code
        if: failure()
        shell: bash
        run: |
          echo "Override exit code"
          exit 0
